name: Install Dependencies

inputs:
  use-sudo:
    description: 'Whether to use sudo for package installation'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        case "${{ inputs.use-sudo }}" in
          true)  SUDO_CMD="sudo" ;;
          false) SUDO_CMD="" ;;
          *) echo "Invalid value for use-sudo: ${{ inputs.use-sudo }}" && exit 1 ;;
        esac

        $SUDO_CMD apt-get update
        $SUDO_CMD apt-get install -y gperf cmake autoconf automake libtool
        $SUDO_CMD apt-get install -y python3-pip python3-venv

    - name: Install MacOS Dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install automake cmake libtool

    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install --upgrade pip build wheel setuptools delocate

