name: 'Download Yices Release'
description: 'Download and extract Yices release based on version'
inputs:
  yices-version:
    description: 'Yices version to download (e.g. 2.6.5)'
    required: true
  output-path:
    description: 'Directory where Yices will be extracted'
    required: false
    default: '/tmp'
runs:
  using: 'composite'
  steps:
    - name: Download Yices release
      shell: bash
      run: |
        set -euo pipefail

        # Default values
        ARCHIVE="/tmp/yices.tgz"
        EXTRACT_CMD="tar -C ${{ inputs.output-path }} -xzf"

        # Detect OS and architecture
        OS=$(uname -s)
        ARCH=$(uname -m)

        # For Windows detection
        if [ "${OS}" = "MINGW"* ] || [ "${OS}" = "MSYS"* ] || [ "${OS}" = "CYGWIN"* ] || [ -n "${RUNNER_OS:-}" -a "${RUNNER_OS}" = "Windows" ]; then
          OS="Windows"
          ARCHIVE="yices.zip"
          EXTRACT_CMD="7z x -o${{ inputs.output-path }}"
        fi

        # Determine URL based on OS, architecture and version
        case "${{ inputs.yices-version }}-${OS}-${ARCH}" in
          2.6.5-Darwin-x86_64) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.5/yices-2.6.5-x86_64-apple-darwin21.6.0-static-gmp.tar.gz" ;;
          2.6.4-Darwin-x86_64) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.4/yices-2.6.4-x86_64-apple-darwin20.6.0.tar.gz" ;;
          2.6.5-Darwin-arm64) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.5/yices-2.6.5-arm64-apple-darwin22.6.0-static-gmp.tar.gz" ;;
          2.6.4-Darwin-arm64) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.4/yices-2.6.4-arm64-apple-darwin20.6.0.tar.gz" ;;
          2.6.5-Windows-x86_64) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.5/yices-2.6.5-x86_64-unknown-mingw32-static-gmp.zip" ;;
          2.6.4-Windows-x86_64) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.4/yices-2.6.4-x86_64-unknown-mingw32-static-gmp.zip" ;;
          2.6.5-Linux-*) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.5/yices-2.6.5-x86_64-pc-linux-gnu-static-gmp.tar.gz" ;;
          2.6.4-Linux-*) URL="https://github.com/SRI-CSL/yices2/releases/download/Yices-2.6.4/yices-2.6.4-x86_64-pc-linux-gnu.tar.gz" ;;
          *) echo "Unsupported combination: ${{ inputs.yices-version }}-${OS}-${ARCH}" >&2; exit 1 ;;
        esac

        # Download and extract
        echo "Downloading Yices from ${URL}"
        curl -sSL -o "${ARCHIVE}" "${URL}"
        mkdir -p "${{ inputs.output-path }}"
        ${EXTRACT_CMD} "${ARCHIVE}"
