name: build-macos

on:
  workflow_dispatch:
    inputs:
      yices_version:
        description: "Upstream Yices version (e.g. 2.6.5)"
        required: true
  push:
    tags: [ "*.*.*" ]  # e.g. "2.6.5"
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - '.github/workflows/build-mac.yml'
      - '.github/actions/**'

env:
  YICES_VERSION: ${{ github.event.inputs.yices_version || (github.ref_name != 'main' && github.ref_name) || '2.6.4' }}
  WHEEL_VERSION: ${{ github.event.inputs.yices_version || (github.ref_name != 'main' && github.ref_name) || '2.6.4' }}.post${{ github.run_number }}

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Build Yices
      uses: ./.github/actions/build-yices
      with:
        yices-version: ${{ env.YICES_VERSION }}
        output-path: /tmp

    - name: Stage artifacts
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p yices_solver/bin yices_solver/lib

        cp /tmp/yices-${YICES_VERSION}/bin/* yices_solver/bin/
        cp /tmp/yices-${YICES_VERSION}/lib/* yices_solver/lib/

    - name: Build wheel
      shell: bash
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ env.WHEEL_VERSION }}
      run: |
        set -euo pipefail
        echo "Building wheel for yices-solver version ${SETUPTOOLS_SCM_PRETEND_VERSION}"

        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) MIN_OS_VERSION=11_0 ;;
          arm64) MIN_OS_VERSION=14_0 ;;
          *) echo "Unknown architecture: $ARCH" && exit 1 ;;
        esac

        python -m build --wheel \
          --config-setting="--build-option=--plat-name" \
          --config-setting="--build-option=macosx_${MIN_OS_VERSION}_${ARCH}"

    - name: Verify and inspect wheel
      uses: ./.github/actions/verify-wheel
      with:
        wheel-version: ${{ env.WHEEL_VERSION }}
        wheel-dir: dist/

    # repair / tag the wheel for macos
    - name: Delocate wheel
      shell: bash
      run: |

        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) MIN_OS_VERSION=11.0 ;;
          arm64) MIN_OS_VERSION=14.0 ;;
          *) echo "Unknown architecture: $ARCH" && exit 1 ;;
        esac

        delocate-wheel --require-target-macos-version ${MIN_OS_VERSION} -v -w dist/ dist/*.whl

    # upload the finished wheel
    - uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}
        path: dist/*.whl

  test-publish:
    # pypa/gh-action-pypi-publish@release/v1 is docker-based, so needs to run on a recent linux
    runs-on: ubuntu-latest
    needs: build-wheel
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: wheel-macos*
        path: dist/
        # from the docs for download-artifact:
        #   If true, the downloaded artifacts will be in the same directory specified by path.
        # so all the wheels should end up in dist/
        merge-multiple: true

    # automatically discovers wheel files in dist/ and publishes them
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  smoke-test:
    name: test ${{ matrix.os }} / py${{ matrix.py }}
    needs: build-wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
        py: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      # checkout needed to run the test-binaries action
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Wait for PyPI index to be updated
        run: |
          sleep 600

      - name: Install wheel
        shell: bash
        run: |
          set -euo pipefail

          python -m venv venv
          source venv/bin/activate

          pip install -vv \
            --index-url https://test.pypi.org/simple/ \
            "yices-solver==${WHEEL_VERSION}"

      - name: Inspect venv
        shell: bash
        run: |
          ls -la venv/bin/

      - name: Test binaries
        uses: ./.github/actions/test-binaries
        with:
          venv-path: venv

