name: build-macos-wheel

on:
  workflow_dispatch:
    inputs:
      yices_version:
        description: "Upstream Yices version (e.g. 2.6.5)"
        required: true
  push:
    tags: [ "*.*.*" ]  # e.g. "2.6.5"
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - '.github/workflows/build-mac.yml'

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
    env:
      YICES_VERSION: ${{ github.event.inputs.yices_version || (github.ref_name != 'main' && github.ref_name) || '2.6.4' }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Build Yices
      uses: ./.github/actions/build-yices
      with:
        yices-version: ${{ env.YICES_VERSION }}
        output-path: /tmp

    - name: Stage artifacts
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p yices_solver/bin yices_solver/lib

        cp /tmp/yices-${YICES_VERSION}/bin/* yices_solver/bin/
        cp /tmp/yices-${YICES_VERSION}/lib/* yices_solver/lib/

    - name: Build wheel
      shell: bash
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ env.YICES_VERSION }}
      run: |
        set -euo pipefail
        echo "Building wheel for yices-solver version ${SETUPTOOLS_SCM_PRETEND_VERSION}"
        python -m build --wheel

    - name: Verify and inspect wheel
      uses: ./.github/actions/verify-wheel
      with:
        wheel-version: ${{ env.YICES_VERSION }}
        wheel-dir: dist/

    # repair / tag the wheel for macos
    - name: Delocate wheel
      shell: bash
      run: |
        delocate-wheel --require-target-macos-version 11.0 -v -w dist/ dist/*.whl

    # upload the finished wheel
    - uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}
        path: dist/*.whl

  smoke-test:
    name: test ${{ matrix.os }} / py${{ matrix.py }}
    needs: build-wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
        py: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      # download wheels from build job artifacts
      - uses: actions/download-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheels

      - name: Install wheel
        shell: bash
        run: |
          set -euo pipefail

          python -m venv venv
          source venv/bin/activate

          pip install --no-index --find-links=./wheels yices-solver

      - name: Inspect venv
        shell: bash
        run: |
          ls -la venv/bin/

      - name: Test binaries
        uses: ./.github/actions/test-binaries
        with:
          venv-path: venv

