name: build-windows-wheel

on:
  workflow_dispatch:
    inputs:
      yices_version:
        description: "Upstream Yices version (e.g. 2.6.5)"
        required: true
  push:
    tags: [ "*.*.*" ]  # e.g. "2.6.5"
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - '.github/workflows/build-windows.yml'
      - '.github/actions/**'

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      YICES_VERSION: ${{ github.event.inputs.yices_version || (github.ref_name != 'main' && github.ref_name) || '2.6.4' }}
      WHEEL_VERSION: ${{ github.event.inputs.yices_version || (github.ref_name != 'main' && github.ref_name) || '2.6.4' }}.post${{ github.run_number }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build wheel auditwheel setuptools

    - name: Print tool versions
      shell: bash
      run: |
        pip list

    - name: Download Yices release
      uses: ./.github/actions/download-yices
      with:
        yices-version: ${{ env.YICES_VERSION }}
        output-path: /tmp

    - name: Stage artifacts
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p yices_solver/Scripts yices_solver/lib

        # don't copy from lib/, it only contains libyices.a and libyices.dll.a
        # note: libyices.dll is in bin/
        mv /tmp/yices-${YICES_VERSION}/bin/libyices.dll yices_solver/lib/
        mv /tmp/yices-${YICES_VERSION}/bin/* yices_solver/Scripts/

    - name: Build wheel
      shell: bash
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ env.WHEEL_VERSION }}
      run: |
        echo "Building wheel for yices-solver version ${WHEEL_VERSION}"
        python3 -m build --wheel

    - name: Verify wheel version
      uses: ./.github/actions/verify-wheel
      with:
        wheel-version: ${{ env.WHEEL_VERSION }}
        wheel-dir: dist/

    # upload the finished wheel
    - uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}
        path: dist/*.whl

  smoke-test:
    name: test ${{ matrix.os }} / py${{ matrix.py }}
    needs: build-wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        py: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      # checkout needed to run the test-binaries action
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      # download wheels from build job artefacts
      - uses: actions/download-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheels

      - name: Install wheel
        shell: bash
        run: |
          set -euo pipefail

          python -m venv venv
          source venv/Scripts/activate

          pip install --no-index --find-links=./wheels yices-solver

      - name: Inspect venv
        shell: bash
        run: |
          ls -la venv/Scripts/

      - name: Test binaries
        uses: ./.github/actions/test-binaries
        with:
          venv-path: venv
